# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Code\Qt\cnn-eia\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


# noinspection SpellCheckingInspection
class ParametersExtractorGUI(object):
    def __init__(self, main_window):
        main_window.resize(640, 145)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(main_window.sizePolicy().hasHeightForWidth())
        main_window.setSizePolicy(size_policy)
        main_window.setMinimumSize(QtCore.QSize(640, 145))
        main_window.setMaximumSize(QtCore.QSize(640, 145))
        icon = QtGui.QIcon()
        project_dir = __file__.replace("\\", "/").replace("/gui/extract/parameters_extractor_gui.py", "")
        icon.addPixmap(QtGui.QPixmap(project_dir + "/imgs/main-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.modelLocationGB = QtWidgets.QGroupBox(self.centralwidget)
        self.modelLocationGB.setGeometry(QtCore.QRect(10, 10, 421, 71))
        self.modelLocation = QtWidgets.QLineEdit(self.modelLocationGB)
        self.modelLocation.setGeometry(QtCore.QRect(19, 30, 341, 20))
        self.modelLocation.setFrame(True)
        self.modelLocation.setReadOnly(True)
        self.browseButton = QtWidgets.QPushButton(self.modelLocationGB)
        self.browseButton.setGeometry(QtCore.QRect(370, 30, 31, 21))
        self.modelLibraryGB = QtWidgets.QGroupBox(self.centralwidget)
        self.modelLibraryGB.setGeometry(QtCore.QRect(440, 10, 181, 71))
        self.modelLibrary = QtWidgets.QComboBox(self.modelLibraryGB)
        self.modelLibrary.setGeometry(QtCore.QRect(20, 30, 141, 22))
        self.extractButton = QtWidgets.QPushButton(self.centralwidget)
        self.extractButton.setGeometry(QtCore.QRect(440, 90, 181, 31))

        main_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        main_window.setStatusBar(self.statusbar)

        self.set_text(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def set_text(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle("Parameters Extractor")
        self.modelLocationGB.setTitle("Model Location")
        self.browseButton.setText("...")
        self.modelLibraryGB.setTitle("Model Library")
        self.extractButton.setText("Extract Parameters")

    def add_supported_libraries(self, libraries):
        self.modelLibrary.addItem("")
        self.modelLibrary.setItemText(0, "ONNX")

        i = 1
        for lib in libraries:
            self.modelLibrary.addItem("")
            self.modelLibrary.setItemText(i, lib)
            i += 1

        if i == 1:
            self.modelLibrary.setEnabled(False)

    def attach_functionality(self, p_e):
        self.browseButton.clicked.connect(p_e.browse_model_location)
        self.modelLibrary.currentIndexChanged.connect(p_e.model_library_changed)
        self.extractButton.clicked.connect(p_e.extract_model_parameters)
