# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Code\PyCharm\cnn-eia\qt-gui\phase-2-netron_loading\loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import netron

from PyQt5 import QtCore

from gui.export.model_exporter_gui import ModelExporterGUI


class ModelExporter(object):
    def __init__(self, model_path, gui: ModelExporterGUI):
        self.model = model_path
        self.output = model_path[:model_path.rfind('/')]

        self.browser = gui.browser
        netron.start(self.model, browse=False)
        self.browser.setUrl(QtCore.QUrl("http://localhost:8080/"))

    def on_download_requested(self, download):
        download.setPath(self.output + "/model.png")
        download.accept()

    def export_model(self):
        self.browser.page().runJavaScript('this.__view__.export(document.title + ".png");', print)
        # self.browser.page().runJavaScript('this.document.getElementsByClassName("default").length;', print)
        # self.browser.page().runJavaScript('this.document.getElementById("menu-button").remove();', print)
        # self.browser.page().runJavaScript('this.document.getElementById("edge-labels").remove();', print)
        # self.browser.page().runJavaScript('this.document.getElementById("nodes").style.pointerEvents = "none";', print)
