import report_generation.constants as c
import report_generation.writer as w


def generate_basic(map_config, costs, para_index, schedules, arch_info, network_info, schedule_info):
    pdf = w.PDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_font('Arial', 'B', c.h1)
    # header of report
    """ Side Note: Name of Model """
    pdf.cell(0, 10, "{Loop Blocking} Analyzer Report", 1, 0, 'C')
    pdf.ln(c.large_new_line)

    """ Introduction """
    body = """This report generated by CNN-EIA. The goal of this report is analysing the loop blocking of the given Machine Learning Model. The analysis was done on these inputs : """
    w.introduction(body, pdf)
    """
        Input Shape : The input from program
    """
    w.input_shape(pdf, arch_info, network_info, schedule_info)

    """ Glossary"""

    """  
        explanation of memory caches and layer parameters
    """
    w.glossary(arch_info['mem_levels'], pdf)
    pdf.ln(c.meduim_new_line)

    """
        Output 
    """
    pdf.set_font('Arial', 'B', c.h1)
    pdf.cell(0, 10, "Analysis Output  : ", 0, 0, 'L')

    """ 
        Map Configurations
    """
    pdf.ln(c.meduim_new_line)
    pdf.cell(100, 10, "Map Configuration", 1, 1, 'C')
    pdf.ln(c.meduim_new_line)

    # loop blocking

    pdf.cell(50, 10, "Loop Blocking ( factors ): ", "B", 0, 'L')
    w.write_loops(map_config.loop_blockings, pdf)
    pdf.set_font('Arial', '', c.h2)
    pdf.cell(c.width_margin, c.height_margin, "The factors of each loop for each cache.", align="L")
    pdf.ln(c.large_new_line)

    # loop partitioning
    pdf.set_font('Arial', 'B', c.h1)
    pdf.cell(50, 10, "Loop Partitioning ( units ): ", "B", 0, 'L')
    w.write_loops(map_config.loop_partitionings, pdf)
    pdf.set_font('Arial', '', c.h2)
    pdf.cell(c.width_margin, c.height_margin, "Take the processing elements from parallel memories.", align="L")
    pdf.ln(c.large_new_line)

    # loop ordering
    pdf.set_font('Arial', 'B', c.h1)
    pdf.cell(50, 10, "Loop Ordering : ", "B", 0, 'L')
    w.write_loops(map_config.loop_orders, pdf)
    pdf.set_font('Arial', '', c.h2)
    pdf.cell(c.width_margin, c.height_margin, "The order on each cache.", align="L")
    pdf.ln(c.large_new_line)
    pdf.set_font('Arial', 'B', c.h1)

    """ 
        Schedule 
    """

    pdf.cell(100, 10, "Schedule", 1, 1, 'C')
    pdf.ln(c.meduim_new_line)
    pdf.set_font('Arial', 'B', c.h2)
    pdf.cell(100, 10, "The Best format for schedule found is : ")
    pdf.ln(c.meduim_new_line)
    w.write_schedule(schedules, pdf)

    """ 
        Cost Of Each Level 
    """

    pdf.cell(100, 10, "Cost", 1, 1, 'C')
    pdf.ln(c.meduim_new_line)
    w.write_cost_levels(costs, para_index, pdf)

    pdf.output('report_generation/basic_output.pdf', 'F')
