import report_generation.constants as c
import report_generation.writer as w


def generate_basic(map_config, costs, para_index, schedules, arch_info, network_info, schedule_info):
    pdf = w.PDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_font('Arial', 'B', c.h1)
    # header of report
    """ Side Note: Name of Model """
    pdf.cell(0, 10, "Analyzer Report {Loop Blocking}", 1, 0, 'C')
    pdf.ln(c.inter_mid_new_line)
    mem_levels = arch_info['mem_levels']
    """ Introduction """
    body = "This report generated by Convolutional Neural Network Inference Analyzer\n" + \
           "(CNN-IA) to summarize the analysis needed to reach the optimal loop blocking\n" + \
           "for " + network_info['layer_name'] + " using restricted schedule space."

    w.introduction(body, pdf)
    """
        Input Shape : The input from program
    """
    w.to_mem_arch(arch_info, pdf)

    """ Glossary"""

    """  
        explanation of memory caches and layer parameters
    """

    w.glossary(mem_levels, pdf)
    pdf.ln(c.meduim_new_line)

    """
        Output 
    """
    pdf.add_page()
    pdf.set_font('Arial', 'B', c.h1)
    """ 
          Map Configurations
      """
    pdf.cell(100, 10, "Map Configuration", 1, 1, 'C')
    pdf.ln(c.meduim_new_line)

    # loop blocking

    pdf.cell(66, 10, "Loop Blocking (factors):", "B", 0, 'L')
    colored_1 = w.write_loops(map_config.loop_blockings, pdf, list(schedule_info.values())[0])

    # loop partitioning
    pdf.set_font('Arial', 'B', c.h1)
    pdf.cell(69, 10, "Loop Partitioning (units): ", "B", 0, 'L')
    colored_2 = w.write_loops(map_config.loop_partitionings, pdf, list(schedule_info.values())[0])

    # loop ordering
    pdf.set_font('Arial', 'B', c.h1)
    pdf.cell(100, 10, "Loop Ordering (from the innermost): ", "B", 0, 'L')
    colored_3 = w.write_loops(map_config.loop_orders, pdf, list(schedule_info.values())[0])
    pdf.set_font('Arial', 'B', c.h4)
    pdf.ln(c.meduim_new_line)
    if colored_1 or colored_2 or colored_3:
        pdf.set_text_color(0, 128, 0)
        pdf.cell(0, 5, "(Hinted schedule configurations are in green)", 0, 0, 'R')
        pdf.set_text_color(0, 0, 0)
    pdf.set_font('Arial', 'B', c.h1)

    """ 
        Schedule 
    """
    pdf.add_page()
    pdf.cell(100, 10, "Schedule", 1, 1, 'C')
    pdf.ln(c.small_new_line)
    # pdf.set_font('Arial', 'B', c.h2)
    schedule_color = w.write_schedule(schedules, pdf, list(schedule_info.values())[1])
    pdf.set_font('Arial', 'B', c.h4)
    if schedule_color:
        pdf.set_text_color(0, 128, 0)
        pdf.cell(0, 5, "(Hinted loop unrollments are in green)", 0, 0, 'R')
    pdf.set_text_color(0, 0, 0)
    pdf.ln(c.meduim_new_line)
    pdf.set_font('Arial', 'B', c.h1)

    """ 
        Cost Of Each Level 
    """

    pdf.cell(100, 10, "Cost", 1, 1, 'C')
    pdf.ln(c.meduim_new_line)
    pdf.set_font('Arial', 'B', c.h2)
    w.write_cost_levels(costs, para_index, pdf)

    pdf.output('report_generation/basic_output.pdf', 'F')
