import report_generation.constants as c
import report_generation.writer as w


def generate(loop_nest, dataflow_tb, arch_info, network_info):
    pdf = w.PDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_font('Arial', 'B', c.h1)
    # header of report
    """ Side Note: Name of Model """
    pdf.cell(0, 10, "{Dataflow} Analyzer Report", 1, 0, 'C')
    pdf.ln(c.large_new_line)

    """ Introduction """
    body = """This report generated by CNN-EIA. The goal of this report is analysing the dataflow of the given
    Machine Learning Model. The analysis was done on these inputs : """
    w.introduction(body, pdf)
    """
        Input Shape : The input from program
    """
    w.input_shape(pdf, arch_info, network_info)

    """ Glossary"""

    """  
        explanation of memory caches and layer parameters
    """
    w.glossary(arch_info['mem_levels'], pdf)
    pdf.ln(c.meduim_new_line)

    pdf.output('report_generation/dataflow_output.pdf', 'F')
