# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Code\PyCharm\cnn-eia\qt-gui\phase-2-netron\loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


# noinspection PyAttributeOutsideInit,SpellCheckingInspection
class LoadingGUI(object):
    def __init__(self, main_window):
        main_window.setObjectName("MainWindow")
        main_window.resize(320, 60)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(main_window.sizePolicy().hasHeightForWidth())
        main_window.setSizePolicy(size_policy)
        main_window.setMinimumSize(QtCore.QSize(320, 60))
        main_window.setMaximumSize(QtCore.QSize(320, 60))
        icon = QtGui.QIcon()
        project_dir = __file__.replace("\\gui\\netron\\loading_gui.py", "").replace("\\", "/")
        icon.addPixmap(QtGui.QPixmap(project_dir + "/imgs/netron-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 20, 300, 20))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        main_window.setCentralWidget(self.centralwidget)

        main_window.setWindowTitle("Netron Loading")
        QtCore.QMetaObject.connectSlotsByName(main_window)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = LoadingGUI(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
