import reports.constants as c
import reports.writer as w
from verbose.utils import identify_loops_in_brackets_str

def print_tables(pdf, key, loop):
    s = identify_loops_in_brackets_str(key)
    size = len(s)
    pdf.cell(4 * size, 10, s, 1, 0, 'C')
    cost_utlization = "[cost: " + str(loop[0]) + "pJ, utilization: " + str(loop[1]) + "%]"
    pdf.set_font('Arial', '', c.h4)
    pdf.cell(size, 10, border=0, ln=0)
    pdf.cell(70, 10, cost_utlization, 0, 0, 'L')
    pdf.ln(c.large_new_line)
    pdf.set_font('Arial', 'B', c.h1)

    # loop blocking

    pdf.cell(66, 10, "Loop Blocking (factors):", "B", 0, 'L')
    w.write_loops(loop[2].loop_blockings, pdf)

    # loop partitioning
    pdf.set_font('Arial', 'B', c.h1)
    pdf.cell(69, 10, "Loop Partitioning (units): ", "B", 0, 'L')
    w.write_loops(loop[2].loop_partitionings, pdf)

    # loop ordering
    pdf.set_font('Arial', 'B', c.h1)
    pdf.cell(100, 10, "Loop Ordering (from the innermost): ", "B", 0, 'L')
    w.write_loops(loop[2].loop_orders, pdf)


def write_optimality(pdf, loop_nest, dataflow_tb, title, best, hint=False):
    pdf.cell(60, 10, title, 1, 0, 'C')
    if hint:
        pdf.set_font('Arial', '', c.h4)
        pdf.cell(70, 10, "[b: blocking factor, p: partitioning unit]")
    pdf.ln(c.inter_mid_new_line)
    w.write_schedule(loop_nest(dataflow_tb[best][2]), pdf)
    pdf.ln(c.small_new_line)


def write_best_cost_utilization(loop_nest, dataflow_tb, pdf):
    best_cost = best_util = None
    for unrollment in dataflow_tb:
        if best_cost:
            if dataflow_tb[unrollment][0] < dataflow_tb[best_cost][0]:
                best_cost = unrollment
            if dataflow_tb[unrollment][1] > dataflow_tb[best_util][1]:
                best_util = unrollment
        else:
            best_cost = best_util = unrollment

    if best_cost != best_util:
        write_optimality(pdf, loop_nest, dataflow_tb, "Optimal cost", best_cost, True)
        write_optimality(pdf, loop_nest, dataflow_tb, "Optimal utilization", best_util)
    else:
        write_optimality(pdf, loop_nest, dataflow_tb, "Optimal schedule", best_util, True)


def generate(loop_nest, dataflow_tb, arch_info, network_info):
    pdf = w.PDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_font('Arial', 'B', c.h1)
    # header of report
    """ Side Note: Name of Model """
    pdf.cell(0, 10, "Analyzer Report {Dataflow}", 1, 0, 'C')
    pdf.ln(c.inter_mid_new_line)
    mem_levels = arch_info['mem_levels']

    """ Introduction """
    body = "This report generated by Convolutional Neural Network Inference Analyzer " + \
           "(CNN-IA) to summarize the analysis needed to reach the optimal dataflow " + \
           "for " + network_info['layer_name'] + " by exploring common energy-efficient dataflows."

    w.introduction(body, pdf)

    """
         Memory Architecture
    """
    w.to_mem_arch(arch_info, pdf)

    """ Glossary"""

    """  
        explanation of memory caches and layer parameters
    """
    w.glossary(mem_levels, pdf)
    pdf.ln(c.meduim_new_line)

    """
        Output 
    """
    pdf.add_page()
    for key, value in dataflow_tb.items():
        print_tables(pdf, key, value)
        pdf.add_page()

    write_best_cost_utilization(loop_nest, dataflow_tb, pdf)

    pdf.output('reports/dataflow_output.pdf', 'F')
