# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Code\Qt\cnn-eia\loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


# noinspection SpellCheckingInspection
class InterstellarGUI(object):
    def __init__(self, main_window):
        self.model_preview = main_window.parent

        main_window.resize(400, 300)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(main_window.sizePolicy().hasHeightForWidth())
        main_window.setSizePolicy(size_policy)
        main_window.setMinimumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        project_dir = __file__.replace("\\", "/").replace("/gui/requiem/interstellar_gui.py", "")
        icon.addPixmap(QtGui.QPixmap(project_dir + "/imgs/stand-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_window.setWindowIcon(icon)

        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setAutoFillBackground(True)
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("THIS IS REQUIEM!")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.label, 0, 0, 0, 0)

        main_window.setCentralWidget(self.centralwidget)
        main_window.setWindowTitle("Inference Analyzer")
        main_window.show()
